//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGamesDirectory.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Publisher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publisher()
        {
            this.Games = new HashSet<Game>();
        }
    
        public int PublisherId { get; set; }
        [Display(Name = "Name")]
        public string PublisherName { get; set; }
        [Display(Name = "Description")]
        [DataType(DataType.MultilineText)]
        public string PublisherDescription { get; set; }
        public string Nationality { get; set; }
        public string Website { get; set; }
        [Display(Name = "Index Image")]
        public string PublisherImg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Game> Games { get; set; }
    }
}
